export const DataDiskOptions = [
    { text: 'Standard HDD', name: 'Standard HDD', value: 'Standard HDD' },
    { text: 'Standard SSD', name: 'Standard SSD', value: 'Standard SSD' },
    { text: 'Premium SSD', name: 'Premium SSD', value: 'Premium SSD' },
];

export const DiskSizeOptions = [
    { text: '4GB', name: '4GB', value: 4 },
    { text: '8GB', name: '8GB', value: 8 },
    { text: '16GB', name: '16GB', value: 16 },
    { text: '32GB', name: '32GB', value: 32 },
    { text: '64GB', name: '64GB', value: 64 },
    { text: '128GB', name: '128GB', value: 128 },
    { text: '256GB', name: '256GB', value: 256 },
    { text: '512GB', name: '512GB', value: 512 },
    { text: '1024GB', name: '1024GB', value: 1024 },
    { text: '2048GB', name: '2048GB', value: 2048 },
    { text: '4096GB', name: '4096GB', value: 4096 },
    { text: '8192GB', name: '8192GB', value: 8192 },
    { text: '16384GB', name: '16384GB', value: 16384 },
    { text: '32767GB', name: '32767GB', value: 32767 },
];
export const DataDiskHostingCashOptions = [
    { text: 'None', name: 'None', value: 'None' },
    { text: 'ReadOnly', name: 'ReadOnly', value: 'ReadOnly' },
    { text: 'ReadWrite', name: 'ReadWrite', value: 'ReadWrite' },
];

export  const LetterDiskWindows = [
    { text: 'G', name: 'G', value: 'G' },
    { text: 'H', name: 'H', value: 'H' },
    { text: 'I', name: 'I', value: 'I' },
    { text: 'J', name: 'J', value: 'J' },
    { text: 'K', name: 'K', value: 'K' },
    { text: 'L', name: 'L', value: 'L' },
    { text: 'M', name: 'M', value: 'M' },
    { text: 'N', name: 'N', value: 'N' },
    { text: 'O', name: 'O', value: 'O' },
    { text: 'P', name: 'P', value: 'P' },
    { text: 'Q', name: 'Q', value: 'Q' },
    { text: 'R', name: 'R', value: 'R' },
    { text: 'S', name: 'S', value: 'S' },
    { text: 'T', name: 'T', value: 'T' },
    { text: 'U', name: 'U', value: 'U' },
    { text: 'V', name: 'V', value: 'V' },
    { text: 'W', name: 'W', value: 'W' },
    { text: 'X', name: 'X', value: 'X' },
    { text: 'Y', name: 'Y', value: 'Y' },
    { text: 'Z', name: 'Z', value: 'Z' },
];
//for testing:
//["Standard_B2ms","Standard_B2s", "Standard_B4ms", "Standard_B8ms"];

export const VM_Sizes_No_PremiumSSD = 
["Standard_A1_v2",
"Standard_A2_v2",
"Standard_A4_v2",
"Standard_A8_v2",
"Standard_A2m_v2",
"Standard_A4m_v2",
"Standard_A8m_v2",
"Standard_DC8_v2",
"Standard_D1_v2",
"Standard_D2_v2",
"Standard_D3_v2",
"Standard_D4_v2",
"Standard_D5_v2",
"Standard_D2_v3",
"Standard_D4_v3",
"Standard_D8_v3",
"Standard_D16_v3",
"Standard_D32_v3",
"Standard_D2_v4",
"Standard_D4_v4",
"Standard_D8_v4",
"Standard_D16_v4",
"Standard_D32_v4",
"Standard_D48_v4",
"Standard_D64_v4",
"Standard_D2a_v4",
"Standard_D4a_v4",
"Standard_D8a_v4",
"Standard_D16a_v4",
"Standard_D32a_v4",
"Standard_D48a_v4",
"Standard_D64a_v4",
"Standard_D96a_v4",
"Standard_D2d_v4",
"Standard_D4d_v4",
"Standard_D8d_v4",
"Standard_D16d_v4",
"Standard_D32d_v4",
"Standard_D48d_v4",
"Standard_D64d_v4",
"Standard_D2_v5",
"Standard_D4_v5",
"Standard_D8_v5",
"Standard_D16_v5",
"Standard_D32_v5",
"Standard_D48_v5",
"Standard_D64_v5",
"Standard_D96_v5",
"Standard_D2d_v5",
"Standard_D4d_v5",
"Standard_D8d_v5",
"Standard_D16d_v5",
"Standard_D32d_v5",
"Standard_D48d_v5",
"Standard_D64d_v5",
"Standard_D96d_v5",
"Standard_D11_v2",
"Standard_D12_v2",
"Standard_D13_v2",
"Standard_D14_v2",
"Standard_D15_v2",
"Standard_E2_v3",
"Standard_E4_v3",
"Standard_E8_v3",
"Standard_E16_v3",
"Standard_E20_v3",
"Standard_E2a_v4",
"Standard_E4a_v4",
"Standard_E8a_v4",
"Standard_E16a_v4",
"Standard_E20a_v4",
"Standard_E32a_v4",
"Standard_E48a_v4",
"Standard_E64a_v4",
"Standard_E96a_v4",
"Standard_E2d_v4",
"Standard_E4d_v4",
"Standard_E8d_v4",
"Standard_E16d_v4",
"Standard_E20d_v4",
"Standard_E32d_v4",
"Standard_E48d_v4",
"Standard_E64d_v4",
"Standard_E2_v4",
"Standard_E4_v4",
"Standard_E8_v4",
"Standard_E16_v4",
"Standard_E20_v4",
"Standard_E32_v4",
"Standard_E48_v4",
"Standard_E64_v4",
"Standard_E2_v5",
"Standard_E4_v5",
"Standard_E8_v5",
"Standard_E16_v5",
"Standard_E20_v5",
"Standard_E32_v5",
"Standard_E48_v5",
"Standard_E64_v5",
"Standard_E96_v5",
"Standard_E104i_v5",
"Standard_E2d_v5",
"Standard_E4d_v5",
"Standard_E8d_v5",
"Standard_E16d_v5",
"Standard_E20d_v5",
"Standard_E32d_v5",
"Standard_E48d_v5",
"Standard_E64d_v5",
"Standard_E96d_v5",
"Standard_E104id_v5",
"Standard_NC6",
"Standard_NC12",
"Standard_NC24",
"Standard_NC24r",
"Standard_NV6",
"Standard_NV12",
"Standard_NV24"];
